### ISSUE TITLE
[pacman] support loading pre-trained weights

### ISSUE THREAD

**Issue by harrywang** [gamma-lab/buffet#14]
We could train a model and save the network weights in a file and upload to checkpoints for users who do not want to spend time to train.

specify the related hyper parameter values.

```
# save weights
torch.save(q_network.net.state_dict(), './checkpoints/q_network_weights')

# load weights
q_network.net.load_state_dict(torch.load('./checkpoints/q_network_weights'))
```

**Comment by ml4046** [comment]
How about we just specify the parameters in the README.md?

**Comment by harrywang** [comment]
sure
