### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by leon0707** [gamma-lab/buffet#6]
I use python 3.6 to test it. Seems like it is on top of python 3.5.

Please specify the correct python version.
* add short introduction on how to install python 3.5 and build python 3.5 virtual environment if user doesn't have python 3.5.

<img width="955" alt="screen shot 2018-09-19 at 3 07 46 pm" src="https://user-images.githubusercontent.com/523684/45775471-dd705480-bc1d-11e8-9a4c-4f7e79b59c0e.png">

**Comment by harrywang** [comment]
I think 3.6 is ok. 
<img width="578" alt="screen shot 2018-09-19 at 3 17 45 pm" src="https://user-images.githubusercontent.com/595772/45775892-2a085f80-bc1f-11e8-8380-713122d39155.png">

**Comment by harrywang** [comment]
these are warnings - if it does not break things - let's ignore them for now.

**Comment by leon0707** [comment]
```
/.../python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/.../python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
```
